
-- Create the main table for public profiles
CREATE TABLE public.public_psychologist_profiles (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    psychologist_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    custom_url text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT false,
    seo_title text,
    seo_description text,
    seo_keywords text,
    about_description text,
    therapeutic_approach text,
    years_experience integer,
    profession_type text NOT NULL DEFAULT 'psychologist'::text,
    profile_data jsonb,
    view_count integer NOT NULL DEFAULT 0,
    last_viewed_at timestamp with time zone
);

-- Add comments to the table and columns
COMMENT ON TABLE public.public_psychologist_profiles IS 'Stores expanded public profile data for professionals.';
COMMENT ON COLUMN public.public_psychologist_profiles.custom_url IS 'Unique, user-friendly URL for the public profile.';

-- Enable Row Level Security
ALTER TABLE public.public_psychologist_profiles ENABLE ROW LEVEL SECURITY;

-- Create indexes for performance
CREATE INDEX idx_public_psychologist_profiles_psychologist_id ON public.public_psychologist_profiles(psychologist_id);
CREATE INDEX idx_public_psychologist_profiles_custom_url ON public.public_psychologist_profiles(custom_url);

-- Create the join table for specialties
CREATE TABLE public.profile_specialties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    profile_id uuid NOT NULL REFERENCES public.public_psychologist_profiles(id) ON DELETE CASCADE,
    specialty_id uuid NOT NULL REFERENCES public.specialties(id) ON DELETE CASCADE
);

-- Enable Row Level Security for profile_specialties
ALTER TABLE public.profile_specialties ENABLE ROW LEVEL SECURITY;

-- Create indexes for join table
CREATE INDEX idx_profile_specialties_profile_id ON public.profile_specialties(profile_id);
CREATE INDEX idx_profile_specialties_specialty_id ON public.profile_specialties(specialty_id);

-- RLS Policies for public_psychologist_profiles

-- Public can read active profiles
CREATE POLICY "Enable read access for all users on active profiles"
ON public.public_psychologist_profiles
FOR SELECT
USING (is_active = true);

-- Owners can read their own profiles, active or not
CREATE POLICY "Enable read access for profile owners"
ON public.public_psychologist_profiles
FOR SELECT
USING (auth.uid() = psychologist_id);

-- Owners can insert their own profile
CREATE POLICY "Enable insert for authenticated users for their own profile"
ON public.public_psychologist_profiles
FOR INSERT
WITH CHECK (auth.uid() = psychologist_id);

-- Owners can update their own profile
CREATE POLICY "Enable update for users for their own profiles"
ON public.public_psychologist_profiles
FOR UPDATE
USING (auth.uid() = psychologist_id)
WITH CHECK (auth.uid() = psychologist_id);

-- RLS Policies for profile_specialties

-- Public can read specialties of public profiles
CREATE POLICY "Enable read access for all users on profile specialties"
ON public.profile_specialties
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.public_psychologist_profiles p
    WHERE p.id = profile_id AND p.is_active = true
  )
);

-- Owners can manage their own profile's specialties
CREATE POLICY "Enable insert for profile owners"
ON public.profile_specialties
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.public_psychologist_profiles p
    WHERE p.id = profile_id AND p.psychologist_id = auth.uid()
  )
);

CREATE POLICY "Enable delete for profile owners"
ON public.profile_specialties
FOR DELETE
USING (
  EXISTS (
    SELECT 1
    FROM public.public_psychologist_profiles p
    WHERE p.id = profile_id AND p.psychologist_id = auth.uid()
  )
);

-- Function to increment view count
CREATE OR REPLACE FUNCTION increment_profile_view(profile_url TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.public_psychologist_profiles
  SET
    view_count = view_count + 1,
    last_viewed_at = now()
  WHERE custom_url = profile_url;
END;
$$;
